---
# The Travis CI build for this project.

# Don't build tagged commits. Tags are used to mark releases.
branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

language: minimal

# The tests will be run in Docker containers, to verify compatibility with various OS's.
sudo: required
services:
  - docker

env:
  global:
    - TAG=test-vim-setswitch

install:
    # Build the image.
  - make build

script:
  # Run the tests in Vim and Neovim.
  - make

after_script:
  # Inspect the management host environment post-test to aid in debugging.
  - pwd
  - ls -la ../
  - ls -la ./

    # Inspect the Docker container post-test to aid in debugging.
  - docker exec -ti ${TAG} /bin/bash -c 'tree -CghpuI plugged ~/.vim'

    # Clean up after the test.
  - make clean
